[package]
name = "clmm_pool"
edition = "2024"

[addresses]
clmm_pool = "0x0"

[dev-dependencies]

[dev-addresses]

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "framework/mainnet"
override = true

[dependencies.move_stl]
git = "https://github.com/LFBuild/FullSail-CLMM-SC.git"
subdir = "move_stl"
rev = "main"
override = true